### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by Brendan-csel** [azuwey/solid-material-ui#1]
Just checking in to see if this is a project you see progressing or need help with?

If so, I'd like to find out more about your strategy for attacking this - and if I can help.  If not, I might start something similar from scratch.  

As an aside I just completed [solid-bootstrap](https://solid-libs.github.io/solid-bootstrap/#/) which was a much less ambitious project to tackle than MUI.

**Comment by azuwey** [comment]
Hi, the project is not dead, I just really don't have/had to work on it, but this should change in the coming weeks.
Help is always welcome, the plan is to first create basic components, card, buttons, labels and so on. I can create kanban board with the planned components, which can be implement by you or anyone who wanna contribute to this project, and maybe I can create a contribution guide as well, let me know if sounds interesting to you.

**Comment by Brendan-csel** [comment]
Thanks for the reply and great to hear there are plans to progress this.

Are you doing this as a file-by-file port from another project or starting each component from scratch?

**Comment by azuwey** [comment]
I'm starting each component basically from scratch, I'm only using the specification from [here](https://material.io/components?platform=web). But I'm thinking about switching to the v3 docs.

**Comment by Brendan-csel** [comment]
Interesting.  I see that spec also provides [web components](https://github.com/material-components/material-web) with all the correct behaviour (keyboard, accessibility, etc).   

It seems like quite a few of the ["material" projects are basically wrappers](https://material.io/develop/web/guides/framework-wrappers) for those components.

That would certainly make it easier than writing all the Aria and behaviour stuff from scratch.

**Comment by azuwey** [comment]
I agree with you, it would be easier and less work, but in this project I would like to rewrite it from scratch.

**Comment by Brendan-csel** [comment]
I understand - a big undertaking.  I'm not sure I have that much time so I will probably not be any use to you sorry.  I may attempt a wrapper version or perhaps a port to leverage the work already done out there for a quick result.  

I will certainly monitor your progress and wish you all the best as you work through this.
